[package]
name = "nats-proto"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []
client = []
server = []

[dependencies]
itoa = "1.0.1"
nom = { version = "7.1.1", default-features = false } # 0.1s faster compile without 'std' feature
simdutf8 = { version = "0.1.3" }
