[package]
name = "uringy"
version = "0.3.0"
documentation = "https://docs.rs/uringy"
repository = "https://github.com/Dennis-Krasnov/Uringy"
homepage = "https://github.com/Dennis-Krasnov/Uringy"
description = "A simple single-threaded async runtime for Rust based on io_uring."
categories = ["asynchronous", "concurrency", "filesystem", "os", "network-programming"]
keywords = ["io", "async", "non-blocking", "futures", "io_uring"]
license = "MIT"
authors = ["Dennis Krasnov <dennis@krasnov.dev>"]
edition = "2021"
rust-version = "1.58.1"

[workspace]
members = [
    "benchmark",
]

[features]
default = ["fs", "time"]
fs = []
quic = [] # TODO: pulls in quiche dependency
process = []
time = []

[dependencies]
# TODO: loosen dependencies
noop-waker = "=0.1.0"
slab = "0.4.6"
libc = "=0.2.124"
io-uring = { git = "https://github.com/Dennis-Krasnov/io-uring" }

[dev-dependencies]
async-channel = "=1.6.1"
impls = "1.0.3"
