[package]
name = "uringy"
version = "0.1.0"
documentation = "https://github.com/Dennis-Krasnov/Uringy"
repository = "https://github.com/Dennis-Krasnov/Uringy"
homepage = "https://github.com/Dennis-Krasnov/Uringy"
description = "Single-threaded async runtime based on io_uring."
categories = ["asynchronous", "concurrency", "filesystem", "os", "network-programming"]
keywords = ["io", "async", "non-blocking", "futures", "io_uring"]
license = "MIT"
authors = ["Dennis Krasnov <dennis@krasnov.dev>"]
edition = "2021"

[workspace]
members = [
    "benchmark",
]

[dependencies]
concurrent-queue = "1.2.2"

waker-fn = "1.1.0"
async-task = "4.0.3"

libc = "0.2.103"
futures-lite = "1.12.0"
scoped-tls = "1.0.0"

[dev-dependencies]
async-channel = "1.6.1"
