# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "limit_concurrency"
version = "0.1.0"
edition = "2018"

[dependencies]
uringy = { path = "../.." }
async-lock = "2.4.0"
async-channel = "1.6.1"
async-io = "1.6.0"
futures-intrusive = "^0.4"
