[package]
name = "uringy-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
uringy = { path = "../.." }
nats-proto = { path = "./proto", features = ["client"] }
bipbuffer = "0.1.2"
json = "0.12.4"
fastrand = "1.8.0"

[dev-dependencies]
impls = "1.0.3"
