name: Uringy Macros CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - macros/**

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          key: macros-unit-test

      - name: Unit test
        run: cargo test --package uringy-macros
