name: Uringy CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - macros/**

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fix rust
        run: rustup update stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          key: unit-test

      - name: Unit test
        run: cargo test --features http

  build_timings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fix rust
        run: rustup update stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          key: unit-timings

      - name: Download Cargo dependencies
        run: cargo fetch

      - name: Time cold build
        run: cargo build --release --timings

      - name: Upload timings report
        uses: actions/upload-artifact@v3
        with:
          name: build_timings_report
          path: target/cargo-timings/cargo-timing.html

  verify_msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          key: verify-msrv

      - name: Verify whether MSRV is satisfiable
        run: |
          cargo install cargo-msrv
          cargo msrv verify